#!/bin/sh /etc/rc.common

START=99
STOP=10

DIR=/usr/local/home/root/meda
MEDA=$DIR/meda

start() {
    mkdir -p /tmp/mseed
    $MEDA $DIR/config-test.json > /tmp/meda.log 2>&1 &
    logger -t meda "meda avviato"
}

stop() {
    killall meda 2>/dev/null
    logger -t meda "meda fermato"
}
